service: cognito-auth

frameworkVersion: ">=1.5.0"
package:
  exclude:
    - CognitoUserPool

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-northeast-1
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: auth/hello
          method: post
          integration: lambda
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:<REGION>:<AWS_ACCOUNT_ID>:userpool/<USER_POOL_ID>"
            claims:
              - email
  goodNight:
    handler: handler.goodNight
    events:
      - http:
          path: auth/good-night
          method: post
          integration: lambda
          cors: true
          authorizer:
            arn: "arn:aws:cognito-idp:<REGION>:<AWS_ACCOUNT_ID>:userpool/<USER_POOL_ID>"
            claims:
              - email
